### ISSUE TITLE
Add .github folder with files for Contributing, Issues, Code of Conduct, and Pull Requests.

### ISSUE THREAD

**Issue by marshallj** [CodeForNC/reentry-resources-hub#4]
# Tasks:

* [x] Add .github folder
* [ ] Add and markup CONTRIBUTING.md
* [x] Add and markup ISSUES_TEMPLATE.md 
* [x] Add and markup PULL_REQUEST_TEMPLATE.md 
* [x] Add and markup CODE_OF_CONDUCT.md

**Comment by ejaxon** [comment]
@marshallj I find myself deleting the template boilerplate. While admitting that makes me a terrible person, I think it also indicates that we want to rethink the template a bit.

One possibility is to create sections for discussions, features, and bugs and tell users to go ahead and delete the sections that don't apply (i.e., delete the feature & bug sections if you're starting a discussion).

**Comment by marshallj** [comment]
@ejaxon great feedback. I'll work on this.

**Comment by marshallj** [comment]
@ejaxon I took a stab at making the suggested changes to the issue template in the content arch branch. Please feel free to change or update now or as we go. First time at doing this, so not married to any of it. The goal should be to make it easier for others to participate, and get the info we need on the (hopefully) first try so we don't waste time. 

@jhibbets Any opensource.com advice on github templates or contributing documentation?

**Comment by ejaxon** [comment]
Good - I think this will work better. I'll keep thinking about it as I create issues. I'm also aware that the issues I'm creating at this initial stage are probably a bit atypical.

Two further comments. I'm not sure context should get a separate section. Maybe ask for it as part of the description or some other section? Also, might be worth letting people know they can delete sections that are not relevant (e.g., how to reproduce the bug if it's not a bug). I don't have strong feelings about either, just thoughts.

**Comment by jhibbets** [comment]
I don't really have any best practices for templates. Sorry.

**Comment by marshallj** [comment]
Pull-Request template complete. @ejaxon we haven't vetted this one yet. Feel free to add feedback here, or commit changes to the template as needed.

**Comment by ejaxon** [comment]
I think this is all good except the "Types of Change" section. Since you're requiring them to connect to an issue, which already specifies this, it's unnecessary work.

This template obviously makes clear what needs to be covered in CONTRIBUTING.

**Comment by marshallj** [comment]
Removed 'Types of Change'. Will move to CONTRIBUTING next.

**Comment by ejaxon** [comment]
Closing this - we have rough versions of all the docs - we can iterate from here. Also trying to set up a new set of issues going forward per our discussion earlier today @marshallj
